const uiTypes = {
  OPEN_SIDEBAR: "OPEN_SIDEBAR",
  CLOSE_SIDEBAR: "CLOSE_SIDEBAR",
  SET_LAST_DISPLAYED_PROFILE: "SET_LAST_DISPLAYED_PROFILE",
  SET_LANGUAGE: "SET_LANGUAGE"
};

export default uiTypes;
