const recipeTypes = {
  CREATE_RECIPE: "CREATE_RECIPE",
  FETCH_RECIPE_DATA: "FETCH_RECIPE_DATA",
  SET_RECIPE_DATA: "SET_RECIPE_DATA",
  LIKE_RECIPE: 'LIKE_RECIPE',
  DISLIKE_RECIPE: 'DISLIKE_RECIPE',
  DELETE_RECIPE: 'DELETE_RECIPE',
  VIEW_RECIPE: "VIEW_RECIPE",
  ADD_COMMENT: "ADD_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",
  DELETE_STORE_COMMENT: "DELETE_STORE_COMMENT",
  ADD_STORE_COMMENT: "ADD_STORE_COMMENT",
  FETCH_COMMENTS: "FETCH_COMMENTS",
  SET_COMMENTS: "SET_COMMENTS",
  LIKE_COMMENT: "LIKE_COMMENT",
  DISLIKE_COMMENT: "DISLIKE_COMMENT",
}

export default recipeTypes;