const loadingTypes = {
  LOAD_RECIPES: "LOAD_RECIPES",
  LOAD_RECIPE_DATA: "LOAD_RECIPE_DATA",
  LOAD_AUTH: "LOAD_AUTH",
  LOAD_RELATED_RECIPES: "LOAD_RELATED_RECIPES",
  LOAD_HOME_RECENT_RECIPES: "LOAD_HOME_RECENT_RECIPES",
  LOAD_HOME_POPULAR_RECIPES: "LOAD_HOME_POPULAR_RECIPES",
  LOAD_COLLECTION: "LOAD_COLLECTION",
  LOAD_BANNER: 'LOAD_BANNER',
};

export default loadingTypes;
