const loadingTypes = {
  LOAD_RECIPES: "LOAD_RECIPES",
  LOAD_RECIPE_DATA: "LOAD_RECIPE_DATA",
  LOAD_AUTH: "LOAD_AUTH",
  LOAD_RELATED_RECIPES: "LOAD_RELATED_RECIPES",
  LOAD_HOME_RECENT_RECIPES: "LOAD_HOME_RECENT_RECIPES",
  LOAD_HOME_POPULAR_RECIPES: "LOAD_HOME_POPULAR_RECIPES",
  LOAD_COLLECTION: "LOAD_COLLECTION",
  LOAD_BANNER: 'LOAD_BANNER',
  LOAD_TOP_USERS: "LOAD_TOP_USERS",
  LOAD_PROFILE_PIC: "LOAD_PROFILE_PIC",
  LOAD_DELETE_ACCOUNT: "LOAD_DELETE_ACCOUNT"
};

export default loadingTypes;
