const recipesTypes = {
  FETCH_RECIPES: "FETCH_RECIPES",
  SET_QUERY_RECIPES: "SET_QUERY_RECIPES",
  SET_MAIN_RECIPES: "SET_MAIN_RECIPES",
  SET_POPULAR_RECIPES: "SET_POPULAR_RECIPES",
  SET_MY_RECIPES: "SET_MY_RECIPES",
  SET_FAVORITE_RECIPES: "SET_FAVORITE_RECIPES",
  SET_USER_RECIPES: "SET_USER_RECIPES",
  RESET_RECIPES: "RESET_RECIPES",
  SET_SCROLL_DISTANCE: 'GET_SCROLL_DISTANCE',
  SET_MAIN_SCROLL_DISTANCE: "SET_MAIN_SCROLL_DISTANCE",
  SET_POPULAR_SCROLL_DISTANCE: "SET_POPULAR_SCROLL_DISTANCE",
  SET_MY_SCROLL_DISTANCE: "SET_MY_SCROLL_DISTANCE",
  SET_FAVORITE_SCROLL_DISTANCE: "SET_FAVORITE_SCROLL_DISTANCE",
  SET_USER_SCROLL_DISTANCE: "SET_USER_SCROLL_DISTANCE",
  RESET_SCROLL_DISTANCES: 'RESET_SCROLL_DISTANCES',
  SET_POPULAR_TYPE_FILTER: "SET_POPULAR_TYPE_FILTER",
  SET_POPULAR_STATS_FILTER: "SET_POPULAR_STATS_FILTER",
  SET_RECENT_FILTER: "SET_RECENT_FILTER",
};

export default recipesTypes;
