const recipesTypes = {
  FETCH_RECIPES: "FETCH_RECIPES",
  SET_RECIPES: "SET_RECIPES",
  CREATE_RECIPE: "CREATE_RECIPE",
  FETCH_RECIPE_DATA: "FETCH_RECIPE_DATA",
  SET_RECIPE_DATA: "SET_RECIPE_DATA",
  LIKE_RECIPE: 'LIKE_RECIPE',
  DISLIKE_RECIPE: 'DISLIKE_RECIPE',
  DELETE_RECIPE: 'DELETE_RECIPE',
};

export default recipesTypes;
