const collectionsTypes = {
  FETCH_COLLECTION: "FETCH_COLLECTION",
  SET_COLLECTION: "SET_COLLECTION",
  FETCH_BANNER_DATA: "FETCH_BANNER_DATA",
  SET_BANNER: "SET_BANNER",
  FETCH_TOP_USERS: "FETCH_TOP_USERS",
  SET_TOP_USERS: "SET_TOP_USERS",
  SET_ACTIVE_USERS: "SET_ACTIVE_USERS",
}

export default collectionsTypes;